# Generated by Django 5.2.5 on 2025-08-31 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('address', models.TextField()),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('contact', models.BigIntegerField()),
                ('image', models.TextField()),
                ('email_id', models.TextField()),
            ],
        ),
    ]
